### ISSUE TITLE
Measure client resource requirements

### ISSUE THREAD

**Issue by dennis-tra** [dennis-tra/punchr#17]
I believe the requirements are very low - but it would be nice to have numbers and confirm that they can easily run on, e.g., a Raspberry Pi.

**Comment by dennis-tra** [comment]
**Go**
- `mem` - `~100MB`
- `CPU` - `~2.5%`

**Comment by mxinden** [comment]
Running the rust-client based on https://github.com/dennis-tra/punchr/pull/25 for 3 minutes:

- `storage`: 0 MB (does not access the disc)
- `mem`: Peak RSS memory 19,8 MB
- `CPU`
    ```
    $ ps -C rust-client  -o %cpu
    %CPU
    0.2
    ```
    (As in the percentage of time spent on the CPU.)

I don't think the numbers above are particularly meaningful, especially since the rust-client success rate is low. That said, I don't think there is much to worry about resource-usage-wise.

**Comment by dennis-tra** [comment]
Thanks Max, this here was just to make sure it's not excessive and rather a sanity check of what we expected anyways :) I'll close this and update the README 👍
